### PR TITLE
distill useWeb3Connect hook to simplify the connection

### PR DESCRIPTION
**Pull request by gasolin**
Trying to distill a reusable `useWeb3Connect` hook for reuse, might contribute to [eth-hooks](https://github.com/austintgriffith/eth-hooks) later

New to typescript so not sure if its the proper way to refer the type

### CODE REVIEW

**Comment by wslyvh** [comment]
Hi, thanks for contributing again! 

I does look quite clean. I do wonder if all types are necessary this way. But I also feel a little bit; 'if it's not broken, don't fix it'. 
Have you contributed to eth-hooks already? Might be more interesting to create such hooks there and eventually replace all web3 logic with those hooks.

**Comment by gasolin** [comment]
@wslyvh yeah that approach make sense. Will close the PR.

I contribute the useWeb3Modal hook there https://github.com/PaulRBerg/create-eth-app/pull/79/files 
web3Modal integrate more connection method, provides `MetaMask + Wallet Connect` by default

**Comment by wslyvh** [comment]
Thanks for understanding. 

A hook that allows for both Metamask/Web3 + Wallet Connect would be nice and a great addition though! 
If you want to work on that?

**Comment by gasolin** [comment]
@wslyvh sure will do

**Pull request closed without merging**
